### ISSUE TITLE
How to install and run without nanobox?

### ISSUE THREAD

**Issue by xaero7** [phalcon/rest-api#31]
How to install and run without nanobox?

**Comment by jenovateurs** [comment]
You can use docker or follow the documentation to install Phalcon on your webserver:
[Phalcon Docs](https://docs.phalcon.io/4.0/en/installation)

**Comment by xaero7** [comment]
I've setup the Phalcon4, php7.2, nginx, mysql and so on
But no Nanobox or Docker enviorment. Can it run?
I've tried to run , but it got something error:
```
Stack trace:
#0 /var/www/rest-api/vendor/vlucas/phpdotenv/src/Loader.php(83): Dotenv\Loader->ensureFileIsReadable()
#1 /var/www/rest-api/vendor/vlucas/phpdotenv/src/Dotenv.php(114): Dotenv\Loader->load()
#2 /var/www/rest-api/vendor/vlucas/phpdotenv/src/Dotenv.php(81): Dotenv\Dotenv->loadData(true)
#3 /var/www/rest-api/library/Core/autoload.php(37): Dotenv\Dotenv->overload()
#4 /var/www/rest-api/api/public/index.php(15): require_once('/var/www/rest-a...')
#5 {main}
  thrown in /var/www/rest-api/vendor/vlucas/phpdotenv/src/Loader.php on line 106" while reading response header from upstream, client: 10.0.10.171, server: default, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "10.0.10.116:8001"
2020/02/14 19:10:06 [error] 17716#17716: *78 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Phalcon\Tag\Exception: A dependency injection container is required to access the 'url' service in phalcon/Tag.zep:504
Stack trace:
#0 [internal function]: Phalcon\Tag::getUrlService()
#1 [internal function]: Phalcon\Tag::linkTo(Array)
#2 [internal function]: Phalcon\Debug->getVersion()
#3 [internal function]: Phalcon\Debug->onUncaughtException(Object(Dotenv\Exception\InvalidPathException))
#4 {main}
  thrown in phalcon/Tag.zep on line 504" while reading response header from upstream, client: 10.0.10.171, server: default, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "10.0.10.116:8001"
2020/02/14 19:10:08 [error] 17716#17716: *78 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Phalcon\Tag\Exception: A dependency injection container is required to access the 'url' service in phalcon/Tag.zep:504
Stack trace:
#0 [internal function]: Phalcon\Tag::getUrlService()
#1 [internal function]: Phalcon\Tag::linkTo(Array)
#2 [internal function]: Phalcon\Debug->getVersion()
#3 [internal function]: Phalcon\Debug->onUncaughtException(Object(Dotenv\Exception\InvalidPathException))
#4 {main}
  thrown in phalcon/Tag.zep on line 504" while reading response header from upstream, client: 10.0.10.171, server: default, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "10.0.10.116:8001"
```

**Comment by xaero7** [comment]
I've done something as following:
```
1. git clone
2. composer install
3. set the site root: root /var/www/rest-api/api/public;
```

**Comment by xaero7** [comment]
Could someone give an example of `.env` file?

**Comment by niden** [comment]
@xaero7 https://github.com/phalcon/rest-api/tree/master/storage/ci

**Comment by xaero7** [comment]
It works! Thanks!
